# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parliaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('links', django_extensions.db.fields.json.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('names', django_extensions.db.fields.json.JSONField(default=dict)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('links', django_extensions.db.fields.json.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('names', django_extensions.db.fields.json.JSONField(default=dict)),
                ('chamber', models.PositiveSmallIntegerField(choices=[(1, 'House of Commons'), (2, 'Senate'), (3, 'Joint committee')])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='parliaments.Session')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='HouseVote',
            fields=[
                ('links', django_extensions.db.fields.json.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(db_index=True)),
                ('context', django_extensions.db.fields.json.JSONField(default=dict)),
                ('result', models.PositiveSmallIntegerField(choices=[(1, 'Negatived'), (2, 'Agreed To'), (3, 'Tie')])),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_votes', to='proceedings.Bill')),
            ],
            options={
                'ordering': ('sitting__date', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='HouseVoteParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_vote', models.PositiveSmallIntegerField(choices=[(1, 'Nay'), (2, 'Yea'), (3, 'Paired'), (4, 'Abstained')])),
                ('house_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_vote_participants', to='proceedings.HouseVote')),
                ('parliamentarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_vote_participants', to='parliaments.Parliamentarian')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_vote_participants', to='parliaments.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('links', django_extensions.db.fields.json.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('names', django_extensions.db.fields.json.JSONField(default=dict)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(null=True)),
                ('actual_end', models.DateTimeField(null=True)),
                ('location', django_extensions.db.fields.json.JSONField(default=dict)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Audio only'), (2, 'Televised'), (2, 'In Camera'), (3, 'No Broadcast'), (4, 'Travel')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Adjourned'), (2, 'Cancelled'), (3, 'Not Started')])),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='proceedings.Committee')),
            ],
            options={
                'ordering': ('scheduled_start', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('links', django_extensions.db.fields.json.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=5)),
                ('date', models.DateField(unique=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sittings', to='parliaments.Session')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='sitting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='proceedings.Sitting'),
        ),
        migrations.AddField(
            model_name='housevote',
            name='sitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_votes', to='proceedings.Sitting'),
        ),
        migrations.AddField(
            model_name='bill',
            name='committees',
            field=models.ManyToManyField(related_name='bills', to='proceedings.Committee'),
        ),
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='parliaments.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='sitting',
            unique_together=set([('session', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='housevoteparticipant',
            unique_together=set([('house_vote', 'parliamentarian')]),
        ),
    ]
