# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='riding',
            unique_together=set([]),
        ),
    ]
