# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20170501_1509'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='riding',
            unique_together=set([('name', 'province')]),
        ),
    ]
