# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20170501_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentarian',
            name='birthdate',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='parliamentarian',
            name='birthtext',
            field=models.CharField(db_index=True, default='', help_text='Exact birth dates for parliamentarians in the 1800s sometimes omitted day or month', max_length=10),
            preserve_default=False,
        ),
    ]
